### PR TITLE
Server

### PR DESCRIPTION
**Pull request by Southern**
#10 should be merged before this PR.

### CODE REVIEW

**Comment by ScarletTanager** [comment]
Since the fix in #10 is already in the master, do you mind merging the master into this branch and seeing if the build passes?

**Comment by Southern** [comment]
I'll rebase this branch and take that commit out sometime today.

**Comment by ScarletTanager** [comment]
Test server depends on gorilla/mux, I updated .travis.yml to pull that in.

**Comment by Southern** [comment]
:+1:

**Comment by swathivangoor** [comment]
LGTM

**Pull request merged**
