### PR TITLE
Created basic travis.yml

### PR DESCRIPTION
**Pull request by ScarletTanager**
Adds a basic .travis.yml - compilation only with go 1.4.2, no ginkgo/code coverage yet.

### CODE REVIEW

**Comment by ScarletTanager** [comment]
We'll need to get travis to install swig (and its prereqs) as the next step.  Until then, builds will fail.

**Comment by Southern** [comment]
Have you started working on the SWIG installation yet?

**Comment by ScarletTanager** [comment]
It installs swig now, need to get it to update the PATH to include /usr/local/bin

**Comment by ScarletTanager** [comment]
SWIG and PCRE install fine now.  we're getting errors which are, I think, related to the typemaps.  I'm going to pull the spaces out of the typemap and see if that gets it to build.

**Comment by ScarletTanager** [comment]
Okay, now all that's missing is actually getting the FIPS-capable OpenSSL installed and the environment modified to link to it.  I'll do that tonight.  We're close - all the tests pass except for the FIPS-specific ones!

**Comment by ScarletTanager** [comment]
NOTE: DO NOT MERGE THIS BRANCH UNTIL I HAVE THE FIPS-CAPABLE OPENSSL INSTALLED BY TRAVIS.

**Comment by ScarletTanager** [comment]
So getting the linker to work using LD_LIBRARY_PATH isn't working - something to do with the way travis spawns workers, or so it seems.  I will have to update the install_openssl.sh script to update ld.so.conf instead.  Also, the install_openssl.sh script could use some trimming.

**Comment by Southern** [comment]
Could you just `export LD_LIBRARY_PATH` in the install_openssl.sh script? That should be the same as putting it in a .bash_profile or equivalent.

**Comment by ScarletTanager** [comment]
No - that will only apply to child processes of the script.  Travis will never see that variable once the script exits.

**Comment by ScarletTanager** [comment]
The reason .bash_profile/.profile, etc. work is that they are sourced, not exec'd, so they aren't spawned as child processes, and the variables in them are available in the current process.  The before_install: scripts aren't sourced.  I have a couple of ideas to try this morning, will update.

**Comment by ScarletTanager** [comment]
So I had missed a detail of the travis config - if you have this:
env:
- VAR1=val
- VAR2=val
  It triggers two builds, one with VAR1, one with VAR2.  You have to combine them on a single line:
  env:
- VAR1=val VAR2=val
  to get a single build with all variables set (what we wanted).  All checks passing!

**Pull request merged**
